# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/158-HqyYjThrLEsDqu_MH16RMJwrp8cBs
"""

import operator
import os
from typing import Annotated, List, Tuple, Union, Dict, Any, Literal
from typing_extensions import TypedDict
from langchain_core.messages import BaseMessage
from langchain_core.tools import tool
from langchain_community.vectorstores import Chroma
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_core.documents import Document
from bs4 import BeautifulSoup
import requests
import re
from urllib.parse import urljoin, urlparse
from langgraph.graph import StateGraph, END
from dotenv import load_dotenv
import shutil
import logging
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.options import Options as ChromeOptions
import time

# Import domain detection helper
from .domain_helper import integrate_smart_domain_detection
from .hybrid_retriever import create_hybrid_retriever, HybridRetriever
# Add this with your other imports at the top
from .smart_retriever import create_smart_retriever

# Setup logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

load_dotenv()

USE_CHECKPOINTING = False
memory = None
logger.info("Running without checkpointing")

class AgentState(TypedDict):
    url: str
    prompt: str
    mode: str
    answer: str
    error: str
    documents: List[Document]
    visited_urls: List[str]
    urls_to_visit: List[str]
    hybrid_retriever: Any
    chunks: List[Document]
    vectorstore: Any
    max_depth: int
    raw_text: str
    is_valid_url: bool
    is_safe_content: bool
    safety_check_passed: bool
    smart_retriever: Any

@tool
def validate_url_tool(url: str) -> bool:
    """Validates if a given URL is accessible and well-formed."""
    try:
        parsed_url = urlparse(url)
        if not all([parsed_url.scheme, parsed_url.netloc]):
            return False
        response = requests.head(url, allow_redirects=True, timeout=5)
        return response.status_code == 200
    except requests.exceptions.RequestException as e:
        logger.warning("URL validation failed for {}: {}".format(url, e))
        return False

def check_content_safety(text: str, llm) -> Tuple[bool, str]:
    """Uses LLM to check if content is safe and appropriate."""
    try:
        logger.info("🔍 Checking content safety with LLM...")

        sample_text = text[:5000]

        safety_prompt = """Analyze this content for safety issues. Be strict.

Content:
{}

Check for:
1. Sexual/adult content
2. Hate speech
3. Violence/illegal content
4. Scams/malware
5. Harassment material

Respond with ONLY: SAFE or UNSAFE
If UNSAFE, explain briefly why.""".format(sample_text)

        response = llm.invoke(safety_prompt).content.strip().upper()

        if "SAFE" in response and "UNSAFE" not in response:
            logger.info("✅ Content passed safety check")
            return True, "Content is safe"
        else:
            logger.warning("⚠️ Content failed safety check")
            return False, "Content flagged as unsafe: {}".format(response[:100])

    except Exception as e:
        logger.error("Safety check error: {}".format(e))
        return False, "Safety check failed: {}".format(str(e))

def clean_text(text: str) -> str:
    """Clean and normalize text for better processing."""
    try:
        text = re.sub(r'\s+', ' ', text)
        text = re.sub(r'(skip to content|subscribe|follow us|contact us)\s*', '', text, flags=re.IGNORECASE)
        return text.strip()
    except Exception as e:
        logger.error("Error cleaning text: {}".format(e))
        return text

def extract_structured_data(soup: BeautifulSoup, url: str) -> List[str]:
    """
    Universal structured data extraction from any webpage.
    Captures key information like prices, numbers, dates, headings, etc.
    """
    structured_data = []

    try:
        # 1. Extract all headings (h1-h6) with their text
        for i in range(1, 7):
            headings = soup.find_all('h{}'.format(i))
            for h in headings[:5]:  # Top 5 headings per level
                text = h.get_text(strip=True)
                if text and len(text) > 3:
                    structured_data.append("HEADING: {}".format(text))

        # 2. Extract all numbers with context (prices, quantities, dates, etc.)
        number_patterns = [
            (r'(?:Rs\.?\s*|₹\s*)?([\d,]+\.?\d*)', 'PRICE/NUMBER'),
            (r'\$\s?([\d,]+\.?\d*)', 'PRICE/NUMBER'),
            (r'([\d,]+\.?\d+)%', 'PERCENTAGE'),
            (r'\b(\d{1,2}[-/]\d{1,2}[-/]\d{2,4})\b', 'DATE'),
        ]

        text_content = soup.get_text()
        for pattern, label in number_patterns:
            matches = re.findall(pattern, text_content)
            for match in matches[:20]:
                structured_data.append("{}: {}".format(label, match))

        # 3. Extract tables
        tables = soup.find_all('table')
        for idx, table in enumerate(tables[:3], 1):
            rows = table.find_all('tr')
            for row in rows[:10]:
                cells = row.find_all(['td', 'th'])
                if len(cells) >= 2:
                    row_text = ' | '.join([cell.get_text(strip=True) for cell in cells])
                    if row_text:
                        structured_data.append("TABLE_ROW: {}".format(row_text))

        # 4. Extract meta tags
        meta_desc = soup.find('meta', attrs={'name': 'description'})
        if meta_desc and meta_desc.get('content'):
            structured_data.append("META_DESCRIPTION: {}".format(meta_desc.get('content')))

        # 5. Extract financial/stock data classes
        financial_classes = [
            'price', 'stock-price', 'current-price', 'nse-price', 'bse-price',
            'market-cap', 'volume', 'high', 'low', 'change', 'percent-change',
            'value', 'amount', 'total', 'summary', 'stats', 'data'
        ]

        for cls in financial_classes:
            elements = soup.find_all(class_=re.compile(cls, re.IGNORECASE))
            for elem in elements[:5]:
                text = elem.get_text(strip=True)
                if text and len(text) < 200:
                    structured_data.append("{}: {}".format(cls.upper(), text))

        # 6. Extract strong/bold text
        bold_elements = soup.find_all(['strong', 'b'])
        for elem in bold_elements[:20]:
            text = elem.get_text(strip=True)
            if text and 3 < len(text) < 100:
                structured_data.append("IMPORTANT: {}".format(text))

        # 7. Extract list items
        lists = soup.find_all(['ul', 'ol'])
        for lst in lists[:5]:
            items = lst.find_all('li')
            for item in items[:10]:
                text = item.get_text(strip=True)
                if text and 3 < len(text) < 200:
                    structured_data.append("LIST_ITEM: {}".format(text))

        logger.info("✓ Extracted {} structured data points".format(len(structured_data)))

    except Exception as e:
        logger.error("Error extracting structured data: {}".format(e))

    return structured_data

def scrape_with_selenium(url: str, wait_time: int = 15) -> str:
    """Enhanced Selenium scraper with universal data extraction."""
    driver = None
    try:
        logger.info("🌐 Selenium scraping: {}".format(url))

        chrome_options = ChromeOptions()
        chrome_options.add_argument('--headless')
        chrome_options.add_argument('--no-sandbox')
        chrome_options.add_argument('--disable-dev-shm-usage')
        chrome_options.add_argument('--disable-blink-features=AutomationControlled')
        chrome_options.add_argument('--disable-extensions')
        chrome_options.add_argument('--disable-plugins')
        chrome_options.add_argument('user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36')
        chrome_options.add_argument('--disable-gpu')

        driver = webdriver.Chrome(options=chrome_options)
        driver.set_page_load_timeout(20)

        driver.get(url)

        try:
            WebDriverWait(driver, wait_time).until(
                EC.presence_of_element_located((By.TAG_NAME, "body"))
            )
            logger.info("✓ Page body loaded")
        except:
            logger.warning("Timeout waiting for body on {}".format(url))

        time.sleep(7)

        try:
            expand_buttons = driver.find_elements(By.XPATH,
                "//button[contains(translate(., 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz'), 'more')] | "
                "//a[contains(translate(., 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz'), 'read more')] | "
                "//button[contains(translate(., 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz'), 'show')] | "
                "//a[contains(translate(., 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz'), 'view more')]"
            )

            for button in expand_buttons[:3]:
                try:
                    driver.execute_script("arguments[0].scrollIntoView(true);", button)
                    time.sleep(1)
                    driver.execute_script("arguments[0].click();", button)
                    logger.info("✓ Clicked expand button")
                    time.sleep(2)
                except:
                    pass
        except:
            pass

        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        time.sleep(4)
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight/2);")
        time.sleep(3)
        driver.execute_script("window.scrollTo(0, 0);")
        time.sleep(3)

        html_content = driver.page_source
        soup = BeautifulSoup(html_content, 'html.parser')

        structured_data = extract_structured_data(soup, url)

        for script_or_style in soup(['script', 'style', 'nav', 'header', 'footer', 'aside']):
            script_or_style.extract()

        text = soup.get_text()
        text = clean_text(text)

        if structured_data:
            structured_section = "\n".join(structured_data)
            final_text = """
=== STRUCTURED DATA EXTRACTED ===
{}

=== FULL PAGE CONTENT ===
{}
""".format(structured_section, text)
        else:
            final_text = text

        logger.info("✓ Selenium complete: {} chars, {} structured data points".format(len(final_text), len(structured_data)))
        return final_text

    except Exception as e:
        logger.error("Selenium error: {}".format(e))
        return ""
    finally:
        if driver:
            try:
                driver.quit()
            except:
                pass

def scrape_fallback(url: str) -> str:
    """Fallback scraper with structured data extraction."""
    try:
        logger.info("📄 Fallback scraping: {}".format(url))
        response = requests.get(url, timeout=10, headers={
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        })
        response.raise_for_status()
        soup = BeautifulSoup(response.text, 'html.parser')

        structured_data = extract_structured_data(soup, url)

        for script_or_style in soup(['script', 'style', 'nav', 'footer', 'header', 'aside']):
            script_or_style.extract()

        main_content = soup.find('main') or soup.find('article') or soup.find('body')
        if main_content:
            soup = main_content

        text = soup.get_text()
        text = clean_text(text)

        if structured_data:
            structured_section = "\n".join(structured_data)
            final_text = """
=== STRUCTURED DATA EXTRACTED ===
{}

=== FULL PAGE CONTENT ===
{}
""".format(structured_section, text)
        else:
            final_text = text

        logger.info("✓ Fallback complete: {} chars, {} structured data points".format(len(final_text), len(structured_data)))
        return final_text
    except Exception as e:
        logger.error("Fallback scraper error: {}".format(e))
        return ""

@tool
def scrape_and_extract_links_tool(url: str, visited_urls: List[str]) -> Tuple[List[Document], List[str]]:
    """Scrapes URL and extracts links."""
    scraped_documents = []
    new_urls = []

    if url in visited_urls:
        return [], []

    try:
        use_selenium = len(visited_urls) == 0

        if use_selenium:
            full_text = scrape_with_selenium(url, wait_time=15)
        else:
            full_text = scrape_fallback(url)

        if not full_text or len(full_text) < 100:
            logger.warning("Primary scraper returned insufficient content, trying fallback")
            full_text = scrape_fallback(url) if use_selenium else scrape_with_selenium(url, wait_time=10)

        if full_text and len(full_text) > 50:
            doc = Document(
                page_content=full_text,
                metadata={"source": url, "url": url}
            )
            scraped_documents.append(doc)
            logger.info("✓ Document created: {} chars".format(len(full_text)))

        try:
            response = requests.get(url, timeout=8)
            soup = BeautifulSoup(response.text, 'html.parser')

            for a_tag in soup.find_all('a', href=True):
                try:
                    href = a_tag['href']
                    full_url = urljoin(url, href)
                    parsed_full_url = urlparse(full_url)
                    parsed_base_url = urlparse(url)

                    if (parsed_full_url.scheme in ['http', 'https'] and
                        parsed_full_url.netloc == parsed_base_url.netloc and
                        full_url not in visited_urls and
                        '#' not in parsed_full_url.fragment):
                        new_urls.append(full_url)
                except:
                    continue
        except Exception as e:
            logger.warning("Link extraction failed: {}".format(e))

    except Exception as e:
        logger.error("Scrape error: {}".format(e))

    return scraped_documents, list(set(new_urls[:10]))

# ============ LLM AND EMBEDDINGS INITIALIZATION ============

print("\n" + "="*60)
print("INITIALIZING LLM AND EMBEDDINGS")
print("="*60)

gemini_api_key = os.getenv("GEMINI_API_KEY")

if gemini_api_key:
    print("✓ GEMINI_API_KEY found: {}...{}".format(gemini_api_key[:8], gemini_api_key[-4:]))
    os.environ["GOOGLE_API_KEY"] = gemini_api_key
else:
    print("✗ GEMINI_API_KEY not found in .env file")

llm = None
if gemini_api_key:
    try:
        llm = ChatGoogleGenerativeAI(
            model="gemini-2.0-flash-exp",
            google_api_key=gemini_api_key,
            temperature=0.1,
            convert_system_message_to_human=True,
            top_p=0.8,
            top_k=40
        )
        print("✓ Gemini 2.0 Flash LLM initialized successfully")
    except Exception as e:
        print("✗ Error initializing Gemini LLM: {}".format(str(e)))
        logger.error("LLM initialization error: {}".format(e), exc_info=True)
        llm = None
else:
    print("✗ Skipping LLM initialization - no GEMINI_API_KEY found")

embeddings = None
try:
    print("⏳ Initializing embeddings (this may take a moment)...")
    embeddings = HuggingFaceEmbeddings(
        model_name="sentence-transformers/all-MiniLM-L6-v2",
        model_kwargs={'device': 'cpu'},
        encode_kwargs={'normalize_embeddings': True}
    )
    print("✓ HuggingFace embeddings initialized (all-MiniLM-L6-v2)")
except Exception as e:
    print("✗ Error initializing embeddings: {}".format(str(e)))
    logger.error("Embeddings initialization error: {}".format(e), exc_info=True)
    embeddings = None

print("="*60 + "\n")

# ============ WORKFLOW NODES ============

def validate_url_node(state: AgentState) -> Dict[str, Any]:
    """Validates URL format and accessibility"""
    url = state["url"]
    try:
        is_valid = validate_url_tool.invoke(url)
        if is_valid:
            logger.info("✓ URL validated: {}".format(url))
            return {
                "error": "",
                "urls_to_visit": [url],
                "visited_urls": [],
                "is_valid_url": True
            }
        else:
            error_msg = "Invalid or inaccessible URL: {}".format(url)
            logger.warning(error_msg)
            return {"error": error_msg, "is_valid_url": False}
    except Exception as e:
        error_msg = "Error validating URL: {}".format(str(e))
        logger.error(error_msg, exc_info=True)
        return {"error": error_msg, "is_valid_url": False}

def safety_check_node(state: AgentState) -> Dict[str, Any]:
    """Content safety validation using LLM"""
    try:
        documents = state.get("documents", [])

        if not documents:
            logger.warning("No documents to check for safety")
            return {"safety_check_passed": True, "is_safe_content": True}

        first_doc = documents[0]
        is_safe, reason = check_content_safety(first_doc.page_content, llm)

        if is_safe:
            logger.info("✅ Content safety check PASSED")
            return {"safety_check_passed": True, "is_safe_content": True, "error": ""}
        else:
            error_msg = "Content failed safety check: {}".format(reason)
            logger.error(error_msg)
            return {"safety_check_passed": False, "is_safe_content": False, "error": error_msg}

    except Exception as e:
        error_msg = "Safety check error: {}".format(str(e))
        logger.error(error_msg)
        return {"safety_check_passed": False, "is_safe_content": False, "error": error_msg}

def smart_link_prioritization(user_prompt: str, links: List[str], llm, max_links: int = 3) -> List[str]:
    """Uses LLM to intelligently select relevant links"""
    try:
        if not links or not llm:
            return links[:max_links]

        links_text = "\n".join(["{}. {}".format(i+1, link) for i, link in enumerate(links[:15])])

        prioritization_prompt = """You are a web navigation expert. Select the TOP {} most relevant links.

USER QUESTION: {}

AVAILABLE LINKS:
{}

Return ONLY the numbers (comma-separated) of the most relevant links.
Example: 3,7,1

RESPONSE:""".format(max_links, user_prompt, links_text)

        response = llm.invoke(prioritization_prompt).content.strip()

        try:
            selected_indices = [int(num.strip()) - 1 for num in response.split(',') if num.strip().isdigit()]
            selected_links = [links[i] for i in selected_indices if 0 <= i < len(links)]

            if selected_links:
                logger.info("🤖 LLM prioritized {} links".format(len(selected_links)))
                return selected_links[:max_links]
        except:
            pass

        return links[:max_links]

    except Exception as e:
        logger.error("Error in smart link prioritization: {}".format(e))
        return links[:max_links]

def scrape_node(state: AgentState) -> Dict[str, Any]:
    """Scrapes URLs with intelligent link prioritization"""
    try:
        current_url = state["urls_to_visit"][0]
        visited_urls = state.get("visited_urls", [])
        all_documents = state.get("documents", [])
        urls_to_visit = state["urls_to_visit"].copy()
        user_prompt = state.get("prompt", "")

        if len(visited_urls) >= 5:
            logger.info("⚠ Max URLs reached ({})".format(len(visited_urls)))
            return {
                "documents": all_documents,
                "visited_urls": visited_urls,
                "urls_to_visit": []
            }

        logger.info("📄 Scraping URL ({}/5): {}".format(len(visited_urls)+1, current_url))

        scraped_docs, new_links = scrape_and_extract_links_tool.invoke({
            "url": current_url,
            "visited_urls": visited_urls
        })

        all_documents.extend(scraped_docs)
        visited_urls.append(current_url)
        urls_to_visit.pop(0)

        new_links = [link for link in new_links if link not in visited_urls and link not in urls_to_visit]

        if new_links and len(visited_urls) < 5:
            prioritized_links = smart_link_prioritization(
                user_prompt=user_prompt,
                links=new_links,
                llm=llm,
                max_links=3
            )
            urls_to_visit.extend(prioritized_links)
            logger.info("✓ Added {} prioritized links".format(len(prioritized_links)))

        logger.info("✓ Scraped: {} docs, Found: {} links".format(len(scraped_docs), len(new_links)))

        return {
            "documents": all_documents,
            "visited_urls": visited_urls,
            "urls_to_visit": urls_to_visit
        }
    except Exception as e:
        error_msg = "Error in scrape_node: {}".format(str(e))
        logger.error(error_msg, exc_info=True)
        return {
            "documents": state.get("documents", []),
            "visited_urls": state.get("visited_urls", []),
            "urls_to_visit": [],
            "error": error_msg
        }

def vectorize_and_index_node(state: AgentState) -> Dict[str, Any]:
    """Creates vector store with intelligent chunking"""
    try:
        documents = state.get("documents", [])

        if not documents:
            error_msg = "No documents to vectorize."
            logger.warning(error_msg)
            return {"error": error_msg}

        if embeddings is None:
            error_msg = "Embeddings model not initialized."
            logger.error(error_msg)
            return {"error": error_msg}

        logger.info("📚 Vectorizing {} documents...".format(len(documents)))

        text_splitter = RecursiveCharacterTextSplitter(
            chunk_size=800,
            chunk_overlap=150,
            length_function=len,
            separators=["\n\n", "\n## ", "\n", ". ", " ", ""],
            is_separator_regex=False
        )

        chunks = text_splitter.split_documents(documents)

        logger.info("✓ Created {} chunks".format(len(chunks)))

        persist_directory = "./chroma_db"
        
        agent_vector_dir = "./chroma_db/agent_vectors"
        if os.path.exists(agent_vector_dir):

        #if os.path.exists(persist_directory):
            try:
                #shutil.rmtree(persist_directory)
                shutil.rmtree(agent_vector_dir)
            except:
                logger.warning("Could not delete old chroma_db")

        vectorstore = Chroma.from_documents(
            documents=chunks,
            embedding=embeddings,
           # persist_directory=persist_directory
            persist_directory="./chroma_db/agent_vectors"  # ✅ FIXED
        )
        logger.info("✓ Vector store created with {} chunks".format(len(chunks)))
        #  CREATE HYBRID RETRIEVER HERE
        try:
            hybrid_retriever = create_hybrid_retriever(
                vectorstore=vectorstore,
                chunks=chunks,
                adaptive=True,  # Use adaptive alpha
                alpha=0.5  # Default balance
            )
            logger.info("Hybrid retriever initialized")
            # Wrap in SmartRetriever
            smart_retriever = create_smart_retriever(
                base_retriever=hybrid_retriever,
                llm=llm,
                enabled=True,      # Enable smart retrieval
                auto_detect=True   # Auto-detect ambiguous queries
            )
            logger.info("✓ SmartRetriever initialized")

            return {
                "vectorstore": vectorstore,
                "hybrid_retriever": hybrid_retriever,
                "smart_retriever": smart_retriever,
                "chunks": chunks,  #
                "documents": documents,
                "error": ""
            }
        except Exception as e:
            logger.warning("Failed to create hybrid retriever, using vector-only: {}".format(e))
            try:
                vector_retriever = vectorstore.as_retriever(search_kwargs={"k": 20})
                smart_retriever = create_smart_retriever(
                    base_retriever=vector_retriever,
                    llm=llm,
                    enabled=True,
                    auto_detect=True
                )
                logger.info("✓ SmartRetriever initialized (vector-only mode)")

                return {
                    "vectorstore": vectorstore,
                    "hybrid_retriever": None,  # Fallback to None
                    "smart_retriever": smart_retriever,
                    "chunks": chunks,
                    "documents": documents,
                    "error": ""
                }
            except Exception as e2:
                logger.error("Failed to create SmartRetriever: {}".format(e2))
                return {
                    "vectorstore": vectorstore,
                    "hybrid_retriever": None,
                    "smart_retriever": None,
                    "chunks": chunks,
                    "documents": documents,
                    "error": ""
                }
    except Exception as e:
        # If something unexpected bubbles up, capture it
        logger.error("vectorize_and_index_node failed: {}".format(e), exc_info=True)
        return {"error": str(e)}

def query_and_respond_node(state: AgentState) -> Dict[str, Any]:
    """Enhanced query with domain detection and structured data prioritization"""
    try:
        prompt = state["prompt"]
        mode = state.get("mode", "Q&A")
        vectorstore = state.get("vectorstore")
        url = state.get("url", "")

        if not vectorstore:
            return {"answer": "Vector store not initialized.", "error": "Vector store not initialized."}

        if llm is None:
            return {"answer": "LLM not initialized.", "error": "LLM not initialized."}

        logger.info("🔍 Querying for: {}".format(prompt))

        # ============ SMART RETRIEVAL WITH AUTO MULTI-QUERY ============
        smart_retriever = state.get("smart_retriever")
        if smart_retriever:
            logger.info("🧠 Using SmartRetriever (auto multi-query detection)")
            docs = smart_retriever.retrieve(prompt, k=20)

            # Expand if needed
            if len(docs) < 5:
                logger.info("Expanding retrieval to k=30")
                docs = smart_retriever.retrieve(prompt, k=30)
        else:
            logger.info("⚠️ SmartRetriever not available, using fallback")
            # USE HYBRID RETRIEVAL IF AVAILABLE
            hybrid_retriever = state.get("hybrid_retriever")

            if hybrid_retriever:
                logger.info("Using HYBRID retrieval (BM25 + Vector)")
                docs = hybrid_retriever.retrieve(prompt, k=20)

                if len(docs) < 5:
                    # logger.info("Expanding hybrid retrieval to k=30")
                    docs = hybrid_retriever.retrieve(prompt, k=30)
            else:
                # logger.info("Using VECTOR-ONLY retrieval (fallback)")
                retriever = vectorstore.as_retriever(search_kwargs={"k": 20})
                docs = retriever.invoke(prompt)

                if len(docs) < 5:
                    retriever_expanded = vectorstore.as_retriever(search_kwargs={"k": 30})
                    docs = retriever_expanded.invoke(prompt)

            logger.info("Expanded/Final retrieval: {} chunks".format(len(docs)))

        logger.info("Retrieved: {} chunks".format(len(docs)))

        # Remove duplicates
        seen_hashes = set()
        unique_docs = []
        for doc in docs:
            content_hash = hash(doc.page_content.strip())
            if content_hash not in seen_hashes:
                seen_hashes.add(content_hash)
                unique_docs.append(doc)

        docs = unique_docs[:12]
        logger.info("✓ Final: {} unique chunks".format(len(docs)))

        if not docs:
            return {"answer": "No relevant information found.", "error": ""}

        # ============ SMART DOMAIN DETECTION ============
        smart_context = None
        if docs and len(docs) > 0:
            try:
                first_doc_content = docs[0].page_content

                smart_context = integrate_smart_domain_detection(
                    url=url,
                    html_content=first_doc_content,
                    user_prompt=prompt,
                    llm=llm
                )

                logger.info("🎯 Domain: {} ({}% confidence)".format(
                    smart_context['domain'],
                    smart_context['confidence']
                ))

            except Exception as e:
                logger.warning("Domain detection failed, using default: {}".format(str(e)))
                smart_context = None
        # ====================================================

        # Build context - prioritize structured data
        context_parts = []
        for idx, doc in enumerate(docs, 1):
            content = doc.page_content
            if "=== STRUCTURED DATA EXTRACTED ===" in content:
                context_parts.insert(0, "[HIGH PRIORITY CHUNK {}]:\n{}".format(idx, content))
            else:
                context_parts.append("[Chunk {}]:\n{}".format(idx, content))

        context = "\n\n---\n\n".join(context_parts)

        # Use enhanced prompt and instructions if available
        if smart_context and smart_context['confidence'] >= 60:
            extraction_instructions = smart_context['extraction_instructions']
            enhanced_prompt = smart_context['enhanced_prompt']
            logger.info("✅ Using domain-specific instructions")
        else:
            extraction_instructions = ""
            enhanced_prompt = prompt
            logger.info("ℹ️ Using default extraction")

        if mode == "Report":
            logger.info("📋 Generating Report...")

            summaries = []
            for idx, doc in enumerate(docs, 1):
                try:
                    summary_prompt = """Extract information relevant to: {}

Content:
{}

Summarize in 2-3 sentences:""".format(enhanced_prompt, doc.page_content)

                    summary = llm.invoke(summary_prompt).content.strip()
                    summaries.append("[Section {}]:\n{}".format(idx, summary))
                except Exception as e:
                    logger.error("Error summarizing chunk {}: {}".format(idx, e))
                    summaries.append("[Section {}] {}...".format(idx, doc.page_content[:300]))

            combined_summaries = "\n\n".join(summaries)

            domain_context = ""
            if extraction_instructions:
                domain_context = "\n\nDOMAIN-SPECIFIC GUIDELINES:\n{}".format(extraction_instructions)

            report_prompt = """Generate a comprehensive report from these website summaries.

USER REQUEST: {}{}

INFORMATION:
{}

Create a structured report with:
1. Executive Summary
2. Key Information
3. Detailed Analysis
4. Conclusion

Use ONLY information from the summaries. Be specific and detailed.

REPORT:""".format(enhanced_prompt, domain_context, combined_summaries)

            response = llm.invoke(report_prompt)
            answer = response.content

        else:
            logger.info("💬 Generating Q&A Response")

            qa_prompt = """You are a helpful assistant answering questions based on website content.
{}

WEBSITE CONTENT:
{}

USER QUESTION: {}

CRITICAL INSTRUCTIONS:
1. Look for EXACT numbers, prices, and specific data - especially in sections marked "STRUCTURED DATA EXTRACTED" or "HIGH PRIORITY"
2. For numerical data: Report EXACT values with decimals
3. Extract specific facts, names, and details from the content
4. Do NOT include URLs or links in your answer
5. ONLY mention information that IS AVAILABLE in the content
6. NEVER write "This information is not available" unless the user specifically asks for that particular data point
7. If asked for a summary, provide ONLY what you found - don't list missing information
8. Be specific, direct, and use exact values from the content
9. Answer in a natural, conversational way
10. Focus on presenting available information positively

IMPORTANT: Prioritize information from "STRUCTURED DATA EXTRACTED" sections as they contain the most accurate data.

If the user asks for a SUMMARY or OVERVIEW:
- Present only the information that IS available
- Organize it clearly
- DO NOT mention what's missing
- Focus on value and insights

If the user asks for SPECIFIC data (like "What is the Day's High?"):
- Then you can say "This specific information is not available" if it's truly not there

ANSWER:""".format(extraction_instructions, context, enhanced_prompt)

            response = llm.invoke(qa_prompt)
            answer = response.content

        logger.info("✓ Generated response ({} chars)".format(len(answer)))
        return {"answer": answer, "error": ""}

    except Exception as e:
        error_msg = "Error in query_and_respond_node: {}".format(str(e))
        logger.error(error_msg, exc_info=True)
        return {"answer": error_msg, "error": error_msg}

def format_response_node(state: AgentState) -> Dict[str, Any]:
    """Formats the final response"""
    error = state.get("error", "")
    if error:
        return {"answer": "Error: {}".format(error)}
    return {"answer": state.get("answer", "No answer generated.")}

def handle_error_node(state: AgentState) -> Dict[str, Any]:
    """Handles errors during processing"""
    error = state.get("error", "Unknown error")
    return {"answer": "Error: {}".format(error)}

# ============ CONDITIONAL ROUTING FUNCTIONS ============

def should_continue_scraping(state: AgentState) -> Literal["continue_scraping", "check_safety"]:
    """Determines if scraping should continue"""
    urls_to_visit = state.get("urls_to_visit", [])
    visited_urls = state.get("visited_urls", [])

    if urls_to_visit and len(visited_urls) < 5:
        logger.info("🔄 Continuing to scrape ({}/5 done)".format(len(visited_urls)))
        return "continue_scraping"

    logger.info("✅ Scraping complete. Visited {} URLs.".format(len(visited_urls)))
    return "check_safety"

def is_url_valid(state: AgentState) -> Literal["valid", "invalid"]:
    """Check URL validation result"""
    error = state.get("error", "")
    if error:
        return "invalid"
    return "valid"

def is_content_safe(state: AgentState) -> Literal["safe", "unsafe"]:
    """Check content safety"""
    if state.get("safety_check_passed", True):
        return "safe"
    return "unsafe"

# ============ WORKFLOW CONSTRUCTION ============

def create_agent_workflow():
    """Creates the LangGraph workflow"""
    workflow = StateGraph(AgentState)

    # Add all nodes
    workflow.add_node("validate_url", validate_url_node)
    workflow.add_node("safety_check", safety_check_node)
    workflow.add_node("scrape", scrape_node)
    workflow.add_node("vectorize_and_index", vectorize_and_index_node)
    workflow.add_node("query_and_respond", query_and_respond_node)
    workflow.add_node("format_response", format_response_node)
    workflow.add_node("handle_error", handle_error_node)

    workflow.set_entry_point("validate_url")

    # URL Validation
    workflow.add_conditional_edges(
        "validate_url",
        is_url_valid,
        {
            "valid": "scrape",
            "invalid": "handle_error",
        },
    )

    # Scraping with iterative crawling
    workflow.add_conditional_edges(
        "scrape",
        should_continue_scraping,
        {
            "continue_scraping": "scrape",
            "check_safety": "safety_check",
        },
    )

    # Safety Check
    workflow.add_conditional_edges(
        "safety_check",
        is_content_safe,
        {
            "safe": "vectorize_and_index",
            "unsafe": "handle_error",
        },
    )

    # Sequential flow after safety passes
    workflow.add_edge("vectorize_and_index", "query_and_respond")
    workflow.add_edge("query_and_respond", "format_response")
    workflow.add_edge("handle_error", "format_response")
    workflow.add_edge("format_response", END)

    return workflow.compile()

# ============ VECTORSTORE CACHING FOR CHAT ============

vectorstore_cache = {}

def get_or_create_vectorstore(url: str, force_reload: bool = False):
    """Get existing vectorstore or create new one"""
    global vectorstore_cache

    if not force_reload and url in vectorstore_cache:
        logger.info("✓ Using cached vectorstore for {}".format(url))
        return vectorstore_cache[url]

    logger.info("Creating new vectorstore for {}".format(url))
    return None

def execute_workflow_with_cache(url: str, prompt: str, mode: str = "Q&A"):
    """Execute workflow with vectorstore caching and domain detection"""
    global vectorstore_cache

    # Check if we have a cached vectorstore
    cached_vectorstore = vectorstore_cache.get(url)

    if cached_vectorstore and prompt != "Initialize website analysis and prepare for questions":
        # Use cached vectorstore for follow-up queries
        logger.info("✓ Using cached vectorstore for follow-up query")
        try:
            cached_smart = vectorstore_cache.get(url + "_smart")
            if cached_smart:
                logger.info("Using cached SmartRetriever")
                docs = cached_smart.retrieve(prompt, k=20)
                if len(docs) < 5:
                    docs = cached_smart.retrieve(prompt, k=30)
            else:
                cached_hybrid = vectorstore_cache.get(url + "_hybrid")
                if cached_hybrid:
                    logger.info("Using cached HYBRID retriever")
                    docs = cached_hybrid.retrieve(prompt, k=20)
                    if len(docs) < 5:
                        docs = cached_hybrid.retrieve(prompt, k=30)
                else:
                    logger.info("Using cached VECTOR-ONLY retriever")
                    retriever = cached_vectorstore.as_retriever(search_kwargs={"k": 20})
                    docs = retriever.invoke(prompt)

                    if len(docs) < 5:
                        retriever = cached_vectorstore.as_retriever(search_kwargs={"k": 30})
                        docs = retriever.invoke(prompt)

            # Remove duplicates
            seen_hashes = set()
            unique_docs = []
            for doc in docs:
                content_hash = hash(doc.page_content.strip())
                if content_hash not in seen_hashes:
                    seen_hashes.add(content_hash)
                    unique_docs.append(doc)

            docs = unique_docs[:12]

            if not docs:
                return {"answer": "No relevant information found in the cached content.", "error": ""}

            # ============ APPLY DOMAIN DETECTION TO CACHED QUERIES ============
            smart_context = None
            if docs and len(docs) > 0:
                try:
                    first_doc_content = docs[0].page_content
                    smart_context = integrate_smart_domain_detection(
                        url=url,
                        html_content=first_doc_content,
                        user_prompt=prompt,
                        llm=llm
                    )
                    logger.info("🎯 Cached query - Domain: {} ({}% confidence)".format(
                        smart_context['domain'],
                        smart_context['confidence']
                    ))
                except Exception as e:
                    logger.warning("Domain detection failed: {}".format(str(e)))
                    smart_context = None

            # Use enhanced prompt and instructions
            if smart_context and smart_context['confidence'] >= 60:
                extraction_instructions = smart_context['extraction_instructions']
                enhanced_prompt = smart_context['enhanced_prompt']
            else:
                extraction_instructions = ""
                enhanced_prompt = prompt
            # ========================================================================

            # Build context - prioritize structured data
            context_parts = []
            for idx, doc in enumerate(docs, 1):
                content = doc.page_content
                if "=== STRUCTURED DATA EXTRACTED ===" in content:
                    context_parts.insert(0, "[HIGH PRIORITY CHUNK {}]:\n{}".format(idx, content))
                else:
                    context_parts.append("[Chunk {}]:\n{}".format(idx, content))

            context = "\n\n---\n\n".join(context_parts)

            qa_prompt = """You are a helpful assistant answering questions based on website content.
{}

WEBSITE CONTENT:
{}

USER QUESTION: {}

CRITICAL INSTRUCTIONS:
1. Look for EXACT numbers, prices, and specific data - especially in "STRUCTURED DATA EXTRACTED" or "HIGH PRIORITY" sections
2. For numerical data: Report EXACT values with decimals
3. Extract specific facts, names, and details from the content
4. Do NOT include URLs or links in your answer
5. ONLY mention information that IS AVAILABLE in the content
6. NEVER write "This information is not available" unless the user specifically asks for that particular data point
7. If asked for a summary, provide ONLY what you found - don't list missing information
8. Be specific, direct, and use exact values from the content
9. Answer in a natural, conversational way
10. Focus on presenting available information positively

IMPORTANT: Prioritize information from "STRUCTURED DATA EXTRACTED" sections.

If the user asks for a SUMMARY or OVERVIEW:
- Present only the information that IS available
- Organize it clearly
- DO NOT mention what's missing
- Focus on value and insights

If the user asks for SPECIFIC data (like "What is the Day's High?"):
- Then you can say "This specific information is not available" if it's truly not there

ANSWER:""".format(extraction_instructions, context, enhanced_prompt)

            response = llm.invoke(qa_prompt)
            return {"answer": response.content, "error": ""}
        except Exception as e:
            return {"answer": "Error generating response: {}".format(str(e)), "error": str(e)}
    else:
        # Create new vectorstore
        logger.info("Creating vectorstore for URL: {}".format(url))
        workflow = create_agent_workflow()

        initial_state = {
            "url": url,
            "prompt": prompt,
            "mode": mode,
            "answer": "",
            "error": "",
            "documents": [],
            "visited_urls": [],
            "urls_to_visit": [],
            "vectorstore": None,
            "hybrid_retriever": None,
            "smart_retriever": None,
            "chunks": [],
            "max_depth": 3,
            "raw_text": "",
            "is_valid_url": False,
            "is_safe_content": False,
            "safety_check_passed": False
        }

        result = workflow.invoke(initial_state)

        # Cache the vectorstore
        if result.get("vectorstore"):
            vectorstore_cache[url] = result["vectorstore"]
            logger.info("✓ Cached vectorstore for {}".format(url))
        if result.get("hybrid_retriever"):
            vectorstore_cache[url + "_hybrid"] = result["hybrid_retriever"]
            logger.info("✓ Cached hybrid retriever for {}".format(url))
        if result.get("smart_retriever"):
            vectorstore_cache[url + "_smart"] = result["smart_retriever"]
            logger.info("✓ Cached SmartRetriever for {}".format(url))

        return result